name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip show pytest  # Verify pytest is installed

      - name: Run tests
        run: |
          pytest  # Run the tests

      - name: List files
        run: |
          ls -R  # List all files to verify directory structure

      - name: Deploy
        if: success()
        run: |
          # Deployment script here

      - name: Send Slack Notification (Success)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment to production was successful!"}' ${{ secrets.SLACK_SUCCESS_WEBHOOK }}

      - name: Send Failure Notification
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The deployment failed! Check the logs."}' ${{ secrets.SLACK_FAILURE_WEBHOOK }}
